# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: asdds

steps:
- script: echo Hello, World!
  displayName: 'Print Hello, World!'

- script: |
    # Perform disk space check
    df -h /
  displayName: 'Disk Space Check'

- script: |
    # Simulate a health-check command (replace with actual health-check command)
    echo Performing health-check...
    # Example: Check if a service is running
    service_status=$(systemctl is-active myservice)
    if [ "$service_status" = "active" ]; then
      echo "Health-check passed: Service is active."
    else
      echo "Health-check failed: Service is not active."
      exit 1
    fi
  displayName: 'Health-check'
